#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nvidia-xconfig
Version  : 430.14
Release  : 1
URL      : https://github.com/NVIDIA/nvidia-xconfig/archive/430.14.tar.gz
Source0  : https://github.com/NVIDIA/nvidia-xconfig/archive/430.14.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: nvidia-xconfig-bin = %{version}-%{release}
Requires: nvidia-xconfig-man = %{version}-%{release}

%description
nvidia-xconfig: A tool for manipulating X config files, specifically for use by the NVIDIA Linux graphics driver.

%package bin
Summary: bin components for the nvidia-xconfig package.
Group: Binaries

%description bin
bin components for the nvidia-xconfig package.


%package man
Summary: man components for the nvidia-xconfig package.
Group: Default

%description man
man components for the nvidia-xconfig package.


%prep
%setup -q -n nvidia-xconfig-430.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559234577
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1559234577
rm -rf %{buildroot}
%make_install PREFIX=/usr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nvidia-xconfig

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/nvidia-xconfig.1.gz
